'use client';
import {NextPage} from "next";
import Head from "next/head";
import {ExtendedSession} from "@/auth";
import {useSession} from "next-auth/react";
import {useEffect, useState} from "react";
import UserNameForm from "@/components/UserNameForm";


const Home: NextPage = () => {
    const {data: session} = useSession();
    const sessionData = (session as ExtendedSession)

    const [balance, setBalance] = useState(null);

    useEffect(() => {
        if (sessionData) {
            const fetchData = async () => {
                let res = await fetch(`/server/main/api/v1/plugins/vault/balance/me`,
                    {
                        headers: {
                            Authorization: `Bearer ${sessionData.accessToken}`
                        }
                    });

                let user = await res.json();
                setBalance(user.balance);
            };
            fetchData().then(r => console.log(r));
        }
    }, [sessionData]);

    return (<div>
        <Head>
            <title>RaceAssist-web</title>
            <meta name="description" content="Generated by create next app"/>
            <link rel="icon" href="/favicon.png"/>
        </Head>
        {balance}
        <UserNameForm/>
    </div>);
};


// components.
// type interface.
// extend function.
// function.
// recoil.
// selector.
// style.
// ssr ssg isr .
// global function.
export default Home;